"""
Config package initializing core configurations, frozen architecture contract,
and decoupled entity state machines.
"""

from .contract import (
    ALGORITHM_SET,
    FEATURE_SELECTION_DEFAULTS,
    HASH_ALGORITHM,
    API_VERSION_STR,
    API_VERSION,
    TIMESTAMP_FORMAT,
    UUID_VERSION,
    PAGINATION_DEFAULTS,
    HTTP_STATUS_CONVENTIONS,
    METRICS,
    PRIMARY_METRIC_DEFAULTS,
    ARTIFACT_NAMING_PATTERNS,
    STORAGE_DIRECTORIES,
    REPRODUCIBILITY_TOLERANCE,
    TaskType,
    RoleType,
    PermissionType,
    SplitType,
    FeatureSelectionMethod,
    FitDiagnosis,
    PayloadLoggingMode,
    RecommendationStatus,
    ConfidenceLevel,
    SelectionDirection,
    ErrorResponse,
    CursorPaginationResponse,
    CursorPaginationParams,
)

from .state_machines import (
    ProjectState,
    PROJECT_VALID_TRANSITIONS,
    ExperimentState,
    EXPERIMENT_VALID_TRANSITIONS,
    ModelState,
    MODEL_VALID_TRANSITIONS,
    DeploymentState,
    DEPLOYMENT_VALID_TRANSITIONS,
    InvalidStateTransitionError,
    can_transition,
    validate_transition,
    get_valid_transitions,
)

__all__ = [
    "ALGORITHM_SET",
    "FEATURE_SELECTION_DEFAULTS",
    "HASH_ALGORITHM",
    "API_VERSION_STR",
    "API_VERSION",
    "TIMESTAMP_FORMAT",
    "UUID_VERSION",
    "PAGINATION_DEFAULTS",
    "HTTP_STATUS_CONVENTIONS",
    "METRICS",
    "PRIMARY_METRIC_DEFAULTS",
    "ARTIFACT_NAMING_PATTERNS",
    "STORAGE_DIRECTORIES",
    "REPRODUCIBILITY_TOLERANCE",
    "TaskType",
    "RoleType",
    "PermissionType",
    "SplitType",
    "FeatureSelectionMethod",
    "FitDiagnosis",
    "PayloadLoggingMode",
    "RecommendationStatus",
    "ConfidenceLevel",
    "SelectionDirection",
    "ErrorResponse",
    "CursorPaginationResponse",
    "CursorPaginationParams",
    # State Machines
    "ProjectState",
    "PROJECT_VALID_TRANSITIONS",
    "ExperimentState",
    "EXPERIMENT_VALID_TRANSITIONS",
    "ModelState",
    "MODEL_VALID_TRANSITIONS",
    "DeploymentState",
    "DEPLOYMENT_VALID_TRANSITIONS",
    "InvalidStateTransitionError",
    "can_transition",
    "validate_transition",
    "get_valid_transitions",
]
